# Generated by Django 3.1.4 on 2021-03-07 01:11

from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('order', '0001_initial'),
        ('customer', '0001_initial'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('QuoteID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('ExpiryDate', models.DateField(default=quote.models.two_business_days, editable=False)),
                ('ProjectType', models.CharField(blank=True, max_length=100)),
                ('DesiredStartDate', models.DateField(auto_now=True)),
                ('DesiredEndDate', models.DateField(auto_now=True)),
                ('QuoteAccepted', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='Y', max_length=10)),
                ('AddressID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('BusinessContactID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.businesscontact')),
                ('CostID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cost')),
                ('CustomerID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuoteStatus', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityRequested', models.PositiveSmallIntegerField()),
                ('QuoteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quote')),
                ('RateRequested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pricerate')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='QuoteStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.quotestatus'),
        ),
        migrations.AddField(
            model_name='quote',
            name='StoreID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
    ]
