# Generated by Django 3.1.4 on 2021-01-09 21:59

from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuote',
            fields=[
                ('CustomerQuoteID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now=True)),
                ('ExpiryDate', models.DateField(default=quote.models.two_business_days)),
            ],
        ),
    ]
