# Generated by Django 3.1.4 on 2021-01-09 23:02

from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210109_1805'),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquote',
            name='CustomerEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='CustomerFirstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='CustomerLastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='CustomerPhoneNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='DesiredEndDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='DesiredStartDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='EstDeposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='EstSubtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='EstTaxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='EstTotalCost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='ProjectType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='TandCAccepted',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerquote',
            name='ExpiryDate',
            field=models.DateField(default=quote.models.two_business_days, editable=False),
        ),
        migrations.CreateModel(
            name='CustomerQuoteTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityRequested', models.PositiveBigIntegerField()),
                ('CustomerQuoteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.customerquote')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
