# Generated by Django 3.1.4 on 2021-01-09 23:50

from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210109_2157'),
        ('inventory', '0003_auto_20210109_1805'),
        ('quote', '0002_auto_20210109_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessQuote',
            fields=[
                ('BusinessQuoteID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now=True)),
                ('ExpiryDate', models.DateField(default=quote.models.two_business_days, editable=False)),
                ('ProjectType', models.CharField(max_length=100)),
                ('ProjectAddress', models.CharField(max_length=100)),
                ('ProjectCity', models.CharField(max_length=100)),
                ('ProjectProvince', models.CharField(max_length=100)),
                ('ProjectPostalCode', models.CharField(max_length=100)),
                ('ProjectManager', models.CharField(max_length=100)),
                ('ProjectManagerContact', models.CharField(max_length=100)),
                ('ProjectEndDate', models.DateField(blank=True)),
                ('RentalStartDate', models.DateField(blank=True)),
                ('RentalEndDate', models.DateField(blank=True)),
                ('EstTotalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstSubtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstDeposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstTaxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstShippingCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TandCAccepted', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('BusinessClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.businessclient')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessQuoteTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityRequested', models.PositiveBigIntegerField()),
                ('BusinessQuoteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.businessquote')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
