# Generated by Django 3.1.4 on 2021-01-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210110_2023'),
        ('quote', '0003_businessquote_businessquotetools'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquote',
            name='CustomerID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessquote',
            name='DateCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businessquotetools',
            name='QuantityRequested',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerquote',
            name='DateCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerquotetools',
            name='QuantityRequested',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
