# Generated by Django 3.1.4 on 2021-01-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_businessquote_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquote',
            name='Expired',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10),
        ),
    ]
