# Generated by Django 3.1.4 on 2021-01-22 23:18

from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210122_2318'),
        ('retail', '0006_auto_20210122_2318'),
        ('inventory', '0006_auto_20210122_1709'),
        ('customer', '0005_auto_20210122_2318'),
        ('quote', '0006_customerquote_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('QuoteID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('Expired', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('ExpiryDate', models.DateField(default=quote.models.two_business_days, editable=False)),
                ('CustomerFirstName', models.CharField(blank=True, max_length=100)),
                ('CustomerLastName', models.CharField(blank=True, max_length=100)),
                ('CustomerEmail', models.CharField(blank=True, max_length=100)),
                ('CustomerPhoneNumber', models.CharField(blank=True, max_length=100)),
                ('ProjectType', models.CharField(blank=True, max_length=100)),
                ('BusinessProjectAddress', models.CharField(blank=True, max_length=100)),
                ('BusinessProjectCity', models.CharField(blank=True, max_length=100)),
                ('BusinessProjectProvince', models.CharField(blank=True, max_length=100)),
                ('BusinessProjectPostalCode', models.CharField(blank=True, max_length=100)),
                ('BusinessProjectManager', models.CharField(blank=True, max_length=100)),
                ('BusinessProjectManagerContact', models.CharField(blank=True, max_length=100)),
                ('DesiredStartDate', models.DateField(auto_now=True)),
                ('DesiredEndDate', models.DateField(auto_now=True)),
                ('EstTotalCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EstSubtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EstDeposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EstTaxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TandCAccepted', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('CustomerID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('StoreID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='retail.store')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateRequested', models.CharField(blank=True, choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY')], max_length=2)),
                ('QuantityRequested', models.PositiveSmallIntegerField()),
                ('QuoteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quote')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='businessquotetools',
            name='BusinessQuoteID',
        ),
        migrations.RemoveField(
            model_name='businessquotetools',
            name='ToolID',
        ),
        migrations.RemoveField(
            model_name='customerquote',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='customerquotetools',
            name='CustomerQuoteID',
        ),
        migrations.RemoveField(
            model_name='customerquotetools',
            name='ToolID',
        ),
        migrations.DeleteModel(
            name='BusinessQuote',
        ),
        migrations.DeleteModel(
            name='BusinessQuoteTools',
        ),
        migrations.DeleteModel(
            name='CustomerQuote',
        ),
        migrations.DeleteModel(
            name='CustomerQuoteTools',
        ),
    ]
