# Generated by Django 3.1.4 on 2021-02-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210209_2009'),
        ('quote', '0007_auto_20210122_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='BusinessProjectAddress',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='BusinessProjectCity',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='BusinessProjectPostalCode',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='BusinessProjectProvince',
        ),
        migrations.AddField(
            model_name='quote',
            name='AddressID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
    ]
