# Generated by Django 3.1.4 on 2021-03-01 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddressID', models.AutoField(primary_key=True, serialize=False)),
                ('AptSuite', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(default='Canada', max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('BusinessID', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessName', models.CharField(max_length=100)),
                ('BusinessArea', models.CharField(max_length=100)),
                ('BusinessEmail', models.CharField(blank=True, max_length=100)),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessContactRole',
            fields=[
                ('BusinessContactRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessContactRole', models.CharField(max_length=100)),
                ('ModifedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDiscountSchedule',
            fields=[
                ('BusinessDiscountID', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessTier', models.CharField(max_length=100)),
                ('BusinessDiscountPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('ModifedDate', models.DateField(auto_now=True)),
                ('CustomerType', models.CharField(choices=[('P', 'Patron'), ('B', 'Business')], default='P', max_length=3)),
                ('CustomerRating', models.SmallIntegerField(blank=True, default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('CustomerNotes', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('IdentifierTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('IdentifierType', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('PatronID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('ProvinceID', models.AutoField(primary_key=True, serialize=False)),
                ('ProvinceShortName', models.CharField(max_length=20)),
                ('ProvinceLongName', models.CharField(max_length=50)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('PhoneNumberID', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneNumbreType', models.CharField(choices=[('C', 'Cell'), ('H', 'Home'), ('B', 'Business')], max_length=4)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Extension', models.CharField(blank=True, max_length=10, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('IdentifierType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.identifiertype')),
            ],
        ),
        migrations.CreateModel(
            name='PatronPhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModifedDate', models.DateField(auto_now=True)),
                ('PatronID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.patron')),
                ('PhoneNumberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.phonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('BusinessContactID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PrimaryContact', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=3)),
                ('BusinessContactRoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.businesscontactrole')),
                ('BusinessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.business')),
                ('PhoneNumberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.phonenumber')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='BusinessDiscountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.businessdiscountschedule'),
        ),
        migrations.AddField(
            model_name='business',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='IdentifierTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.identifiertype'),
        ),
        migrations.AddField(
            model_name='address',
            name='PhoneNumberID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.phonenumber'),
        ),
        migrations.AddField(
            model_name='address',
            name='ProvinceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.province'),
        ),
    ]
