# Generated by Django 3.1.4 on 2020-12-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now=True)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
                ('HomeNumber', models.CharField(blank=True, default=None, max_length=100)),
                ('CellNumber', models.CharField(max_length=100)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('CreditCardNumber', models.CharField(max_length=100)),
                ('CreditCardType', models.CharField(max_length=100)),
                ('CreditCardName', models.CharField(max_length=100)),
                ('BillingAddress', models.CharField(max_length=100)),
                ('BillingCity', models.CharField(max_length=100)),
                ('BillingProvince', models.CharField(max_length=100)),
                ('BillingPostalCode', models.CharField(max_length=100)),
                ('CustomerRating', models.CharField(blank=True, choices=[('G', 'GOOD'), ('K', 'OK'), ('P', 'POOR')], default=None, max_length=100)),
                ('CustomerNotes', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
