# Generated by Django 3.1.4 on 2021-01-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDiscountSchedule',
            fields=[
                ('BusinessDiscountID', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessTier', models.CharField(max_length=100)),
                ('BusinessDiscountPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('BusinessClientID', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessName', models.CharField(max_length=100)),
                ('BusinessArea', models.CharField(max_length=100)),
                ('BusinessAddress', models.CharField(max_length=100)),
                ('BusinessCity', models.CharField(max_length=100)),
                ('BusinessProvince', models.CharField(max_length=100)),
                ('BusinessPostalCode', models.CharField(max_length=100)),
                ('BusinessPhoneNumber', models.CharField(max_length=100)),
                ('BusinessNumberExtension', models.CharField(blank=True, max_length=100)),
                ('BusinessEmail', models.CharField(max_length=100)),
                ('PrimaryContactName', models.CharField(max_length=100)),
                ('PrimaryContactPhoneNumber', models.CharField(max_length=100)),
                ('PrimaryContactExtension', models.CharField(max_length=100)),
                ('PrimaryContactEmail', models.CharField(max_length=100)),
                ('BusinessNotes', models.TextField(blank=True, default=None)),
                ('BusinessDiscountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.businessdiscountschedule')),
            ],
        ),
    ]
