# Generated by Django 3.1.4 on 2021-01-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_businessclient_businessdiscountschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='PrimaryContactExtension',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
