# Generated by Django 3.1.4 on 2021-01-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210110_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessclient',
            name='BusinessDiscountID',
        ),
        migrations.AddField(
            model_name='customer',
            name='BusinessDiscountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.businessdiscountschedule'),
        ),
        migrations.AddField(
            model_name='customer',
            name='BusinessNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='BusinessPrimaryContact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='BusinessPrimaryContactEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='BusinessPrimaryContactPhoneNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='CustomerType',
            field=models.CharField(blank=True, default='C', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CellNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerRating',
            field=models.CharField(blank=True, choices=[('G', 'GOOD'), ('K', 'OK'), ('P', 'POOR')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='HomeNumber',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
