# Generated by Django 3.1.4 on 2021-01-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210122_2318'),
        ('customer', '0005_auto_20210122_2318'),
        ('quote', '0007_auto_20210122_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessClient',
        ),
    ]
