# Generated by Django 3.1.4 on 2021-01-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_delete_businessclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerType',
            field=models.CharField(blank=True, choices=[('C', 'Customer'), ('B', 'Business')], default='C', max_length=2, null=True),
        ),
    ]
