# Generated by Django 3.1.4 on 2021-02-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210122_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddressID', models.AutoField(primary_key=True, serialize=False)),
                ('AddressType', models.CharField(choices=[('C', 'Customer'), ('B', 'Business'), ('Bi', 'Billing'), ('D', 'Delivery'), ('S', 'Store')], max_length=2)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='BillingAddress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='BillingCity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='BillingPostalCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='BillingProvince',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardType',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='PostalCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Province',
        ),
        migrations.AlterField(
            model_name='customer',
            name='EmailAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='AddressID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
    ]
