# Generated by Django 3.1.4 on 2021-03-07 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceRate', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('ToolID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('ToolName', models.CharField(max_length=100)),
                ('ToolBrand', models.CharField(max_length=100)),
                ('ToolPicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('ItemDescription', models.TextField(blank=True, default='')),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToolCategory', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToolCondition', models.CharField(max_length=100)),
                ('ToolConditionDescription', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToolStatus', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToolSubCategory', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('ToolCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.toolcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ToolPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StartDate', models.DateField(auto_now=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('PriceRateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pricerate')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tool')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='ToolCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.toolcategory'),
        ),
        migrations.AddField(
            model_name='tool',
            name='ToolSubCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.toolsubcategory'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('TimesRented', models.SmallIntegerField(default=0)),
                ('Decomissioned', models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10, null=True)),
                ('DateDecomissioned', models.DateField(blank=True, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('StoreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.store')),
                ('ToolConditionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.toolcondition')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tool')),
                ('ToolStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.toolstatus')),
            ],
        ),
    ]
