# Generated by Django 3.1.4 on 2021-01-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0005_auto_20201231_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ToolID', models.AutoField(primary_key=True, serialize=False)),
                ('ToolName', models.CharField(max_length=100)),
                ('ToolBrand', models.CharField(max_length=100)),
                ('ToolCategory', models.CharField(max_length=100)),
                ('ToolSubCategory', models.CharField(max_length=100)),
                ('HourlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DailyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WeeklyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MonthlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HourlyOverduePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DailyOverduePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WeeklyOverduePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MonthlyOverduePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PictureURL', models.CharField(blank=True, max_length=100)),
                ('NumToolInInventory', models.PositiveIntegerField()),
                ('NumToolAvailable', models.PositiveIntegerField()),
                ('NumToolRented', models.PositiveIntegerField()),
                ('TimesRented', models.PositiveIntegerField()),
                ('ConditionRating', models.CharField(choices=[('G', 'GOOD'), ('DR', 'DAMAGE/REPAIR'), ('D', 'DAMAGED')], default='G', max_length=100)),
                ('Decomissioned', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=100)),
                ('StoreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.store')),
            ],
        ),
    ]
