# Generated by Django 3.1.4 on 2021-03-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210307_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='ShortForm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='toolsubcategory',
            name='ShortForm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
