# Generated by Django 3.1.4 on 2021-01-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210109_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='NumToolAvailable',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='NumToolInInventory',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='TimesRented',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
