# Generated by Django 3.1.4 on 2021-01-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ToolDescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ToolCategory',
            field=models.CharField(choices=[('1', 'Shovels, Picks, Long Handled Tools'), ('2', 'HVAC Equipment'), ('3', 'Concrete and Masonry Equipment'), ('4', 'Drilling and Drilling Accessories'), ('5', 'Floor Care and Sanding'), ('6', 'Scaffolding'), ('7', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ToolSubCategory',
            field=models.CharField(choices=[('1.1', 'Rental Bars'), ('1.2', 'Forks and Rakes'), ('1.3', 'Picks and Handles'), ('2.1', 'Dehumidifiers'), ('2.2', 'Heaters'), ('3.1', 'Concrete Grinders and Surface Prep'), ('3.2', 'Sawing and Drilling Equipment'), ('4.1', 'Drill Bit Sets'), ('4.2', 'Annular Cutting Sets'), ('5.1', 'Sanders & Edgers'), ('5.2', 'Polishers'), ('5.3', 'Grinders'), ('6.1', 'Scafolding Towers'), ('7.1', 'Other')], max_length=100),
        ),
    ]
