# Generated by Django 3.1.4 on 2021-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210110_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='PictureURL',
        ),
        migrations.AddField(
            model_name='inventory',
            name='ToolPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
