# Generated by Django 3.1.4 on 2021-02-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210122_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ConditionRating',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Decomissioned',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='TimesRented',
        ),
        migrations.AddField(
            model_name='inventory',
            name='NumToolRented',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ToolCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('ToolNumber', models.PositiveSmallIntegerField()),
                ('TimesRented', models.PositiveSmallIntegerField()),
                ('ConditionRating', models.CharField(choices=[('G', 'GOOD'), ('DR', 'DAMAGE/REPAIR'), ('D', 'DAMAGED')], default='G', max_length=10)),
                ('Decomissioned', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('DateDecomissioned', models.DateField(blank=True, null=True)),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
