# Generated by Django 3.1.4 on 2021-03-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('EmployeeEmail', models.CharField(blank=True, max_length=100)),
                ('PhoneNumberID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.phonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('PositionID', models.AutoField(primary_key=True, serialize=False)),
                ('PositionName', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreID', models.AutoField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=100)),
                ('AddressID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('PhoneNumberID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.phonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='HQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HQname', models.CharField(max_length=100)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('AddressID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('CEOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employee')),
                ('PhoneNumberID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.phonenumber')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='PositionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employeerole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='StoreID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
    ]
