# Generated by Django 3.1.4 on 2020-12-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20201231_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeEmail',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeePhoneNum',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='StoreID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='AssistantManagerID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assmanager', to='retail.employeerole'),
        ),
    ]
