# Generated by Django 3.1.4 on 2020-12-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_auto_20201231_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='StoreID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
    ]
