# Generated by Django 3.1.4 on 2020-12-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_auto_20201231_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hq',
            name='CEOID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employee'),
        ),
        migrations.AlterField(
            model_name='store',
            name='AssistantManagerID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assmanager', to='retail.employee'),
        ),
        migrations.AlterField(
            model_name='store',
            name='ManagerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='retail.employee'),
        ),
    ]
