# Generated by Django 3.1.4 on 2021-01-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_auto_20201231_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
