# Generated by Django 3.1.4 on 2021-02-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210209_2009'),
        ('retail', '0006_auto_20210122_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hq',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='hq',
            name='City',
        ),
        migrations.RemoveField(
            model_name='hq',
            name='PostalCode',
        ),
        migrations.RemoveField(
            model_name='hq',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='City',
        ),
        migrations.RemoveField(
            model_name='store',
            name='PostalCode',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Province',
        ),
        migrations.AddField(
            model_name='hq',
            name='AddressID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
        migrations.AddField(
            model_name='store',
            name='AddressID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
    ]
