# Generated by Django 3.1.4 on 2021-03-07 01:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChequePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChequeDate', models.DateField()),
                ('PayTo', models.CharField(max_length=100)),
                ('ChequeTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.CharField(max_length=30)),
                ('CCV', models.CharField(max_length=5)),
                ('ExpiryDate', models.DateField()),
                ('CreditCardType', models.CharField(max_length=30)),
                ('CreditCardName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('DueDate', models.DateField(default=datetime.datetime(2021, 4, 6, 1, 11, 51, 654173), editable=False)),
                ('DepositPaid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('DepositRefunded', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('OverdueCharges', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceStatus', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethod', models.CharField(max_length=100)),
                ('PaymentIssuer', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.DateField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('PaymentMethodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
