# Generated by Django 3.1.4 on 2021-03-01 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_auto_20210301_1841'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('DueDate', models.DateField(default=datetime.datetime(2021, 3, 31, 22, 55, 52, 341565), editable=False)),
                ('DepositPaid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('DepositRefunded', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('OverdueCharges', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('CostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cost')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceStatus', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethod', models.CharField(max_length=100)),
                ('PaymentIssuer', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.DateField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('PaymentMethodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceStatusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicestatus'),
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.CharField(max_length=30)),
                ('CCV', models.CharField(max_length=5)),
                ('ExpiryDate', models.DateField()),
                ('CreditCardType', models.CharField(max_length=30)),
                ('CreditCardName', models.CharField(max_length=100)),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.payment')),
            ],
        ),
        migrations.CreateModel(
            name='ChequePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChequeDate', models.DateField()),
                ('PayTo', models.CharField(max_length=100)),
                ('ChequeTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.payment')),
            ],
        ),
    ]
