# Generated by Django 3.1.4 on 2021-03-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('order', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='CostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cost'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceStatusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicestatus'),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='AddressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='PaymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.payment'),
        ),
        migrations.AddField(
            model_name='chequepayment',
            name='PaymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.payment'),
        ),
    ]
