# Generated by Django 3.1.4 on 2021-03-09 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210308_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 0, 2, 29, 870294), editable=False),
        ),
    ]
