# Generated by Django 3.1.4 on 2021-03-10 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210309_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 22, 30, 59, 357279), editable=False),
        ),
    ]
