# Generated by Django 3.1.4 on 2021-03-22 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210322_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 23, 4, 9, 158102), editable=False),
        ),
    ]
