# Generated by Django 3.1.4 on 2021-03-26 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20210322_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 19, 51, 3, 354952), editable=False),
        ),
    ]
