# Generated by Django 3.1.4 on 2021-03-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20210326_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(),
        ),
    ]
