# Generated by Django 3.1.4 on 2021-01-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_auto_20210110_2023'),
        ('retail', '0005_auto_20201231_1725'),
        ('quote', '0004_auto_20210110_2023'),
        ('inventory', '0004_auto_20210110_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrder',
            fields=[
                ('BusinessOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(choices=[('O', 'OPEN'), ('C', 'CLOSED')], default='O', max_length=100)),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('EstimatedEndDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('TandCAccepted', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('TotalOrderCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxesAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepositPaid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('DepositAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepositRefunded', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCharges', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('OrderStatusAfterRefund', models.CharField(choices=[('G', 'GOOD'), ('K', 'OK'), ('P', 'POOR')], default='G', max_length=20)),
                ('OrderNotes', models.TextField(blank=True)),
                ('BusinessClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.businessclient')),
                ('BusinessQuoteID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quote.businessquote')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(choices=[('O', 'OPEN'), ('C', 'CLOSED')], default='O', max_length=100)),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('EstimatedEndDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('TandCAccepted', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('TotalOrderCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxesAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepositPaid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('DepositAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepositRefunded', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCharges', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('OrderStatusAfterRefund', models.CharField(choices=[('G', 'GOOD'), ('K', 'OK'), ('P', 'POOR')], default='G', max_length=20)),
                ('OrderNotes', models.TextField(blank=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('CustomerQuoteID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quote.customerquote')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraFeeSchedule',
            fields=[
                ('ExtraFeeID', models.AutoField(primary_key=True, serialize=False)),
                ('DamageName', models.CharField(max_length=100)),
                ('DamageDescription', models.CharField(max_length=150)),
                ('FeeCost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentalRate', models.CharField(choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY')], max_length=10)),
                ('QuantityRented', models.PositiveSmallIntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.customerorder')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='ExtraFeeID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.extrafeeschedule'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='StoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
        migrations.CreateModel(
            name='BusinessOrderTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentalRate', models.CharField(choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY')], max_length=10)),
                ('QuantityRented', models.PositiveSmallIntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.businessorder')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='businessorder',
            name='ExtraFeeID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.extrafeeschedule'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='StoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
    ]
