# Generated by Django 3.1.4 on 2021-01-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorder',
            name='DepositAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DepositAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
