# Generated by Django 3.1.4 on 2021-03-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quote', '0001_initial'),
        ('order', '0001_initial'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CustomerQuoteID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quote.quote'),
        ),
        migrations.AddField(
            model_name='order',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employee'),
        ),
        migrations.AddField(
            model_name='cost',
            name='TaxCodeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.taxcode'),
        ),
    ]
