# Generated by Django 3.1.4 on 2021-01-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210110_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='OverdueCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
