# Generated by Django 3.1.4 on 2021-03-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210307_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='TaxCodeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.taxcode'),
        ),
    ]
