# Generated by Django 3.1.4 on 2021-01-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210110_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorder',
            name='ExtraFeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.extrafeeschedule'),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='OverdueCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='ExtraFeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.extrafeeschedule'),
        ),
    ]
