# Generated by Django 3.1.4 on 2021-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210322_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='OverdueCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
