# Generated by Django 3.1.4 on 2021-03-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210322_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartDate',
            field=models.DateTimeField(),
        ),
    ]
