# Generated by Django 3.1.4 on 2021-01-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210122_2318'),
        ('inventory', '0006_auto_20210122_1709'),
        ('order', '0005_auto_20210110_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(choices=[('O', 'OPEN'), ('C', 'CLOSED')], default='O', max_length=100)),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('EstimatedEndDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('TandCAccepted', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('TotalOrderCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxesAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('DepositPaid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('DepositAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('DepositRefunded', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCharges', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OrderStatusAfterRefund', models.CharField(choices=[('G', 'GOOD'), ('K', 'OK'), ('P', 'POOR')], default='G', max_length=20)),
                ('OrderNotes', models.TextField(blank=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentalRate', models.CharField(choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY')], max_length=10)),
                ('QuantityRented', models.PositiveSmallIntegerField()),
                ('RentalLength', models.PositiveSmallIntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='businessordertool',
            name='OrderID',
        ),
        migrations.RemoveField(
            model_name='businessordertool',
            name='ToolID',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='CustomerQuoteID',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='EmployeeID',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='ExtraFeeID',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='StoreID',
        ),
        migrations.RemoveField(
            model_name='customerordertool',
            name='OrderID',
        ),
        migrations.RemoveField(
            model_name='customerordertool',
            name='ToolID',
        ),
        migrations.DeleteModel(
            name='BusinessOrder',
        ),
        migrations.DeleteModel(
            name='BusinessOrderTool',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='CustomerOrderTool',
        ),
    ]
