# Generated by Django 3.1.4 on 2021-01-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210122_2318'),
        ('retail', '0006_auto_20210122_2318'),
        ('quote', '0007_auto_20210122_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CustomerQuoteID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quote.quote'),
        ),
        migrations.AddField(
            model_name='order',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='ExtraFeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.extrafeeschedule'),
        ),
        migrations.AddField(
            model_name='order',
            name='StoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.store'),
        ),
    ]
