# Generated by Django 3.1.4 on 2021-03-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210322_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
