# Generated by Django 3.1.4 on 2021-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210322_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
