# Generated by Django 3.1.4 on 2021-02-09 20:09

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210209_2009'),
        ('order', '0007_auto_20210122_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpiryDate', models.DateField(default=order.models.invoice_expiry, editable=False)),
                ('TotalOrderCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxesAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('DepositPaid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10)),
                ('DepositAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('DepositRefunded', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCharges', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('OverdueCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ExtraFeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.extrafeeschedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='DepositAmount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='DepositPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='DepositRefunded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='DiscountAmount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ExtraFeeID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='OverdueCharges',
        ),
        migrations.RemoveField(
            model_name='order',
            name='OverdueCost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='TaxesAmount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='TotalOrderCost',
        ),
        migrations.AddField(
            model_name='order',
            name='AddressID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='ToolRetreival',
            field=models.CharField(blank=True, choices=[('D', 'Delivery'), ('P', 'Pickup')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordertool',
            name='ToolConditionAtRefund',
            field=models.CharField(blank=True, choices=[('G', 'GOOD'), ('DR', 'DAMAGE/REPAIR'), ('D', 'DAMAGED')], max_length=10),
        ),
        migrations.AddField(
            model_name='ordertool',
            name='ToolConditionAtRental',
            field=models.CharField(blank=True, choices=[('G', 'GOOD'), ('DR', 'DAMAGE/REPAIR'), ('D', 'DAMAGED')], max_length=10),
        ),
        migrations.AddField(
            model_name='ordertool',
            name='ToolNum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('PaymentInformationID', models.AutoField(primary_key=True, serialize=False)),
                ('CreditCardNum', models.CharField(max_length=30)),
                ('CreditCardType', models.CharField(choices=[('V', 'VISA'), ('M', 'MASTERCARD'), ('A', 'AMERICAN EXPRESS')], max_length=3)),
                ('CreditCardCustomerName', models.CharField(max_length=100)),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('DatePaid', models.DateField()),
                ('PaymentMethod', models.CharField(choices=[('CC', 'CREDIT CARD'), ('CA', 'CASH')], max_length=5)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.invoice')),
                ('PaymentInformationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.paymentinformation')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
