# Generated by Django 3.1.4 on 2021-03-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210322_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='InventoryID',
        ),
    ]
